### ISSUE TITLE
Multiple site's

### ISSUE THREAD

**Issue by Wamarcaiceloff** [charlie-haley/omada_exporter#100]
My "Default" list does not have access points, they are all broken down by region. How can I get information about all access points in all regions? The global view value could not be used.

**Comment by charlie-haley** [comment]
At the moment, the exporter only supports a single site. Which you can configure with `OMADA_SITE` environment variable or the `--site <site-name>` flag.

If you have multiple sites, I'd recommend deploying multiple instances of the exporter and having 1 per site. This is mostly for performance reasons, as scraping many sites could be quite slow.
However, if there's enough demand we could add multiple sites as a feature to the exporter.

**Comment by Wamarcaiceloff** [comment]
Thanks for the reply, it would be great if such a feature appeared. In the meantime, apparently, I will use several instances.
