### ISSUE TITLE
Duplicate repositories on Docker Hub

### ISSUE THREAD

**Issue by codersaur** [charlie-haley/omada_exporter#12]
There are now two repositories on Docker Hub:
 https://hub.docker.com/r/chhaley/omada-exporter
 https://hub.docker.com/r/chhaley/omada_exporter

[README.md](https://github.com/charlie-haley/omada_exporter#readme) is referencing the old one for Docker and the new one for Helm...?

**Comment by charlie-haley** [comment]
Thanks for raising this, the correct image should be pushed now!
