### ISSUE TITLE
omada_port_* metrics not generated

### ISSUE THREAD

**Issue by codersaur** [charlie-haley/omada_exporter#14]
omada_port_* metrics are not generated.

From a quick scan of the code, it looks like there's a bug in https://github.com/charlie-haley/omada_exporter/blob/main/pkg/omada/handler.go

`if item.Wireless {` logic should be inverted...?

**Comment by codersaur** [comment]
Assuming the above issue is fixed, it looks like port metrics would still only be generated for ports where there is a corresponding client (?). Can I suggest that metrics for all ports are generated?  Hence, maybe standardise the metric name prefixes to relate to the three types of object being reported on:
```
omada_device_*
omada_device_port_*
omada_client_*

```
...which actually makes me wonder if there are any useful metrics that could be collected about the omada controller itself?
`omada_controller_*`

**Comment by charlie-haley** [comment]
Good catch, I'll merge/release a hotfix for the port metrics. I'll close this issue and open a new one for improving the metrics - I'd definitely like them to be a bit more sane. 

Also regading metrics around the controller, it looks like the Omada API exposes a few, I'll see what I can add to the exporter
