### ISSUE TITLE
No client or device metrics with latest omada-controller version

### ISSUE THREAD

**Issue by codersaur** [charlie-haley/omada_exporter#29]
With the latest mbentley/omada-controller:latest the exporter is only returning controller metrics, no client or device metrics. I'm guessing the api must have changed again...?

**Comment by charlie-haley** [comment]
I honestly wouldn't be surprised, the API is a bit of a mess 😆 

What version are you seeing the web interface and what version of the exporter are you running?

I'm currently having no issues on `5.0.30`, but that's with the OC200 if it makes a difference.

**Comment by charlie-haley** [comment]
Okay I've just seen this issue on my end... I'll investigate and hopefully get a fix in ASAP

**Comment by codersaur** [comment]
The version is still reported as "5.0.30" in the web interface, but something has changed....

In the system logs I see the following:

> 03-11-2022 22:06:11.143 WARN [https-jsse-nio-8043-exec-257] [] c.t.s.o.a.d.i.PermissionCheckHandler(84): Current user does not has permission to access this site. path:/236041a....baaa6b9/api/v2/sites/Home/clients, method:GET
> 03-11-2022 22:06:41.136 WARN [https-jsse-nio-8043-exec-242] [] c.t.s.o.a.d.i.PermissionCheckHandler(84): Current user does not has permission to access this site. path:/236041a...aa6b9/api/v2/sites/Home/devices, method:GET

If I log in interactively in the web interface with the prometheus user I can see all the devices and clients, so the user does have the permissions in the web GUI. 

My guess is that something is not right with the request headers when getting these endpoints.

**Comment by charlie-haley** [comment]
Okay, the issue on my end appeared to be because of a badly formed host, I've added a fix for that. (It had a trailing `/` on the end)

Could you check your user and see if `Site Privileges` is configured correctly, maybe try `All` if it's still not working

![image](https://user-images.githubusercontent.com/27928201/158060017-4f05e1c0-fc86-4bdf-9435-46f3e986e6d8.png)


Let me know how you get on, i'll do some further digging if you're still having issues.

**Comment by codersaur** [comment]
Yep, I've checked the user privileges. I've tried setting the Site Privileges option to my specific site and also "All". I also tried changing the name of my default site to "Home", and yesterday I completely rebuilt my omada-controller instance (just restoring the settings), but none of these changes fixed the issue.

I have logged into the Web GUI with the user ("prometheus" in my case) and it can see all the client and device data as you would expect.

I've just tried your 0.4.1 release, but this hasn't resolved the issue. Let me know if there's any more info you need. 

I think I will try rolling back the omada-controller image to confirm it is an issue with the latest image (so long as I can do it without losing stats).

**Comment by phyber** [comment]
After a little bit of looking at what API calls from my browser were doing, I've spotted what's happened here.

The `OMADA_SITE` argument must be the "Site ID" rather than it's name. In my case, I was attempting to use "Home". I changed this to its ID (a long hexadecimal value) and things sprung to life.
There doesn't seem to be a way to find this ID from the Controller UI, so I just pulled it from one of my devices responses in the Firefox Developer Tools.

I guess the exporter needs some extra code to find this ID based on the site name.

**Comment by codersaur** [comment]
Yep, I can also confirm that if you obtain the site_id and put that into the OMADA_SITE variable then it works (however the metrics produced now use the site_id as the site tag, which is not ideal). Either the documentation needs to be updated, or preferably, the code should be updated so that site_name and site_id are handled appropriately (probably want both output as tags in the metrics).

**Comment by charlie-haley** [comment]
Sorry for the slow progress on this guys, life's been getting in the way! 

Awesome that you've found a fix, the Omada API always seems to change under my feet constantly. I'll raise a PR today to implement a lookup for the Site ID. 

Thanks for the investigation on this @phyber @codersaur

**Comment by charlie-haley** [comment]
The latest release should contain the fix, let me know how you get on as I only use a single site for Omada!

I'll re-open the issue if you're still having issues

**Comment by codersaur** [comment]
Just looked at your code. I can see that the sites endpoint returns an "Operation forbidden." error as a Viewer and you are using the "{{omada_base_url}}/api/v2/sites/home/setting/firewall/timeout" endpoint instead. However, this also gives a "Operation forbidden." error on my system, which explains why it's failing to resolve the site_name to site_id.

**Comment by charlie-haley** [comment]
> Just looked at your code. I can see that the sites endpoint returns an "Operation forbidden." error as a Viewer and you are using the "{{omada_base_url}}/api/v2/sites/home/setting/firewall/timeout" endpoint instead. However, this also gives a "Operation forbidden." error on my system, which explains why it's failing to resolve the site_name to site_id.

Hmm, I tested that endoint with my exporter user and it seemed to work. How is your user configured? Is `Site Privileges` set to `All`?

If that still doesn't work I'll try and dig for some alternative endpoints

**Comment by codersaur** [comment]
I think you'll want to use `{{omada_base_url}}/api/v2/users/current` endpoint, see my edit above.

**Comment by charlie-haley** [comment]
Release [v0.4.3](https://github.com/charlie-haley/omada_exporter/releases/tag/v0.4.3) is now fetching from the `user` endpoint

**Comment by codersaur** [comment]
Good work, that seems to have fixed it. Thanks.

One minor request would be to expose both site_name and site_id tags in the prometheus metrics.

**Comment by charlie-haley** [comment]
> Good work, that seems to have fixed it. Thanks.
> 
> One minor request would be to expose both site_name and site_id tags in the prometheus metrics.

No problem, I'll add an issue to the repo
