### ISSUE TITLE
Error when using "insecure"

### ISSUE THREAD

**Issue by alehmann76** [charlie-haley/omada_exporter#36]
Hello,
i´m using the command line version v0.4.3 on a centos 8 server.

as soon as i use the option "--insecure" i get the following error:

`omada-exporter  --host 'https://192.168.xxx.xxx' --port '9202' --site 'Daheim' --interval '30' --username 'exporter' --password 'TopSecret' --disable-go-collector --disable-process-collector --insecure

FATA[0000] invalid character '\x1f' looking for beginning of value`

i also tried the enviroment variable, same result and the docker version shows the same behaviour.

next try: 
--insecure=true   --> same result: error

try the false value:
--insecure=false  --> works with the expected result, that the certificate check fails!

I dont´t know what i´m doing wrong?!? maybe you have an idea?

because it´s just an internal server, i don´t want to setup a certificate

thanks 
Alexander

**Comment by charlie-haley** [comment]
Hi, thanks for raising this issue! 
That's strange, I can't seem to replicate this on my end, could you post the output of `curl -kv https://192.168.xxx.xxx` (feel free to omit the IP adddress)

**Comment by alehmann76** [comment]
@charlie-haley 
Sorry for my late response, but i was quite busy.....
your question showed me the right direction.
i haven´t added the port 8043 to my host because i thought it´s the default port and the exporter will use it!
So now everything is fine and running!  
Great project!
