### ISSUE TITLE
Feature request: Fork and create Netdata collector

### ISSUE THREAD

**Issue by lucianor** [charlie-haley/omada_exporter#51]
Netdata is another monitoring tool that is widely used, and allow collector modules built in Go. 
Would it possible to fork this into a Netdata collector by reusing most of the code?

https://github.com/netdata/go.d.plugin/tree/master/modules/example

An example on how to setup?

**Comment by charlie-haley** [comment]
Unfortunately the scope of this exporter will only extend to Prometheus. I don't use netdata but you're more than welcome to fork the project if you'd like to create a netdata collector

**Comment by jcouzy** [comment]
I am using Prometheus as well, I am trying to use it with Prometheus.
This is how I deploy the Omaha_exporter docker container:

  omada_exporter:
     image: chhaley/omada_exporter
     container_name: omada-exporter
     restart: unless-stopped
     ports:
        - "9202:9202"
     environment:
        - OMADA_HOST=https://omada.infra.local
        - OMADA_INSECURE=true
        - OMADA_SITE=Default
        - OMADA_USER=prometheus
        - OMADA_PASS=*************
     labels:
        - "com.centurylinklabs.watchtower.enable=true"

Container starts, no weird stuff in the container logs. All seems to work well.

time="2022-12-08T14:47:47Z" level=info msg="not logged in, logging in with user: prometheus"
time="2022-12-08T14:47:48Z" level=info msg="listening on :9202"


But, when I go to https://dockerhost:9202/metrics, I get this in my browser:

An error has occurred while serving metrics:

144 error(s) occurred:
* collected metric "omada_port_power_watts" { label:<name:"client" value:"" > label:<name:"profile" value:"All" > label:<name:"site" value:"Default" > label:<name:"site_id" value:"Default" > label:<name:"switch_id" value:"60f03f07447e14066d93e7f9" > label:<name:"switch_mac" value:"00-31-92-76-44-6C" > label:<name:"switch_port" value:"1" > label:<name:"vendor" value:"" > label:<name:"vlan_id" value:"1" > gauge:<value:4.9 > } was collected before with the same name and label values
* collected metric "omada_port_link_status" { label:<name:"client" value:"" > label:<name:"profile" value:"All" > label:<name:"site" value:"Default" > label:<name:"site_id" value:"Default" > label:<name:"switch_id" value:"60f03f07447e14066d93e7f9" > label:<name:"switch_mac" value:"00-31-92-76-44-6C" > label:<name:"switch_port" value:"1" > label:<name:"vendor" value:"" > label:<name:"vlan_id" value:"1" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "omada_port_link_speed_mbps" { label:<name:"client" value:"" > label:<name:"profile" value:"All" > label:<name:"site" value:"Default" > label:<name:"site_id" value:"Default" > label:<name:"switch_id" value:"60f03f07447e14066d93e7f9" > label:<name:"switch_mac" value:"00-31-92-76-44-6C" > label:<name:"switch_port" value:"1" > label:<name:"vendor" value:"" > label:<name:"vlan_id" value:"1" > gauge:<value:1000 > } was collected before with the same name and label values
* collected metric "omada_port_power_watts" { label:<name:"client" value:"" > label:<name:"profile" value:"Disable" > label:<name:"site" value:"Default" > label:<name:"site_id" value:"Default" > label:<name:"switch_id" value:"60f03f07447e14066d93e7f9" > label:<name:"switch_mac" value:"00-31-92-76-44-6C" > label:<name:"switch_port" value:"2" > label:<name:"vendor" value:"" > label:<name:"vlan_id" value:"10" > gauge:<value:0 > } was collected before with the same name and label values
Etc etc….. until all 144 errors have shown.
So I suspect something goes wrong with or the Omaha_exporter, or the collecting of the data.


Met vriendelijke groet / Kind regards,


Johan Couzy

tel:       		+31 6 11 00 04 02
e-mail: 		***@***.***
