### ISSUE TITLE
Context deadline exceeded error

### ISSUE THREAD

**Issue by dvonessen** [charlie-haley/omada_exporter#58]
Hi, 

I am getting following error while starting the exporter.

```bash
time="2022-12-17T06:26:53Z" level=fatal msg="Get \"https://my.domain.redacted:443/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

I did set some variables to configure the exporter:
```env
OMADA_HOST=https://my.domain.redacted:443/
OMADA_USER=omada-exporter
OMADA_SITE=Default
OMADA_INSECURE=True
```

Thank you for your development and support.

**Comment by codersaur** [comment]
I'm seeing this error also when connecting to the metrics endpoint. I'm using mbentley/omada-controller:latest and chhaley/omada_exporter:latest. No errors in the omada_exporter log though.

**Comment by charlie-haley** [comment]
Hi @dvonessen, thanks for raising this! 

Omada enforces some HTTPS redirects, it might be having trouble with the port, could you try setting `OMADA_HOST=https://my.domain.redacted` without the port?

**Comment by dvonessen** [comment]
Hi @charlie-haley, thank you for your answer.

Mhh, long time ago...
I did something wrong, but cannot remember what. But now this issue is not present anymore. The container ist starting and running. 

But it doesn't serve metrics. I do have the same error as in https://github.com/charlie-haley/omada_exporter/issues/55.
I will add a thumbs up to the bug.
