### ISSUE TITLE
Add new client traffic metrics

### ISSUE THREAD

**Issue by jesperdote** [charlie-haley/omada_exporter#68]

**Comment by jesperdote** [comment]
Is there a plan to include these metrics?

**Comment by charlie-haley** [comment]
Hey @jesperdote. Previously these metrics weren't available under the API but it looks like they are now. 

I'll look into doing a new release with some more granular metrics for clients

**Comment by yoniko** [comment]
See #75 for some added client metrics.

**Comment by charlie-haley** [comment]
Fixed in #75
