### ISSUE TITLE
Cert unknow authority

### ISSUE THREAD

**Issue by MaxMaxMaks** [charlie-haley/omada_exporter#76]
It is an option in a Docker image to run with parameters "-e OMADA_INSECURE=true" because I am facing an issue when trying to skip this error: "{"level":"fatal","error":"Get "[https://192.168.105.30\](https://192.168.105.30%5C)": x509: certificate signed by unknown authority","time":"2023-07-26T12:35:22Z","message":"App failed to run"}". When add paramets image can't start.

**Comment by charlie-haley** [comment]
Unless you've generated your own certificate that's been signed by a trusted CA you'll get an error. Running it with `-e OMADA_INSECURE=true` should solve the issue, you said the image won't start with the environment variable set, are there any errors in the logs?

Also, what version of the Omada Controller are you running and what version of the Exporter?

**Comment by MaxMaxMaks** [comment]
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/charlie-haley/omada_exporter/pkg/api.(*Client).getCid(0xc00002d380)
        github.com/charlie-haley/omada_exporter@v0.9.0/pkg/api/auth.go:66 +0x1fc
github.com/charlie-haley/omada_exporter/pkg/api.Configure(0xd27700)
        github.com/charlie-haley/omada_exporter@v0.9.0/pkg/api/api.go:50 +0x8f
github.com/charlie-haley/omada_exporter/cmd.run(0xc0001d0500?)
        github.com/charlie-haley/omada_exporter@v0.9.0/cmd/exporter.go:85 +0x136
github.com/urfave/cli/v2.(*App).RunContext(0xc00019a9c0, {0xa0a528?, 0xc00002a040}, {0xc000022230, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/charlie-haley/omada_exporter/cmd.Run()
        github.com/charlie-haley/omada_exporter@v0.9.0/cmd/exporter.go:54 +0xb34
main.main()
        github.com/charlie-haley/omada_exporter@v0.9.0/main.go:8 +0x17

**Comment by charlie-haley** [comment]
What version of the Omada Controller are you running?

**Comment by MaxMaxMaks** [comment]
5.12.2

Maybe I have don't ON API it is possible ?

śr., 26 lip 2023 o 23:39 Charlie Haley ***@***.***>
napisał(a):

**Comment by charlie-haley** [comment]
It looks like the latest versions of the controller have been [revoked due to bugs in the update](https://community.tp-link.com/en/business/forum/topic/615166). I'd suggest downgrading to `5.9` until the updates are released again

**Comment by MaxMaxMaks** [comment]
Thank you, I didn't notice that the version is different.

wt., 1 sie 2023 o 12:00 Charlie Haley ***@***.***> napisał(a):
