### ISSUE TITLE
App failed to run

### ISSUE THREAD

**Issue by Wamarcaiceloff** [charlie-haley/omada_exporter#99]
Hello @charlie-haley , I have an error when starting the program, and I do not know how to fix it. I am using version exporter 0.13.1 with the 5.14 omada controller.

root@prod-lnx-ap-controller:~/omada_exporter# ./omada-exporter_0.13.1_linux_amd64 --host http://10.0.40.100:8043 --username exporter --password ********
{"level":"fatal","error":"invalid character 'B' looking for beginning of value","time":"2024-08-14T12:20:22+03:00","message":"App failed to run"}

**Comment by charlie-haley** [comment]
Hey @Wamarcaiceloff, is your Omada Controller running on HTTPS? If so, try updating your host to `https://10.0.40.100:8043`. You also may need to use the `--insecure` flag if you're running with the default/self-signed certificates

**Comment by Wamarcaiceloff** [comment]
Thanks!!! Works great
